'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class openABEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=openABEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property AkademischerTitels() As DbSet(Of AkademischerTitel)
    Public Property Anredes() As DbSet(Of Anrede)
    Public Property Berufsfunktions() As DbSet(Of Berufsfunktion)
    Public Property Berufstitels() As DbSet(Of Berufstitel)
    Public Property Firmas() As DbSet(Of Firma)
    Public Property Institutions() As DbSet(Of Institution)
    Public Property Kontakts() As DbSet(Of Kontakt)
    Public Property Lands() As DbSet(Of Land)

    Public Overridable Function setLog() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("setLog")
    End Function

End Class
