'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Kontakt
    Public Property ID As Integer
    Public Property VorName As String
    Public Property NachName As String
    Public Property FK_Land As Nullable(Of Integer)
    Public Property FK_Anrede As Nullable(Of Integer)
    Public Property FK_AkademischerTitel As Nullable(Of Integer)
    Public Property FK_Berufstitel As Nullable(Of Integer)
    Public Property FK_Berufsfunktion As Nullable(Of Integer)
    Public Property FK_Firma As Nullable(Of Integer)
    Public Property FK_Institution As Nullable(Of Integer)
    Public Property Telefon As String
    Public Property MobilTelefon As String
    Public Property AdresseStrasse As String
    Public Property AdresseOrt As String
    Public Property AdressePLZ As String
    Public Property EmailPrivat As String
    Public Property EmailFirma As String
    Public Property HomePage As String

    Public Overridable Property Firmas As Firma

End Class
